In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, roc_curve, classification_report, confusion_matrix
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml

# Load data from https://www.openml.org/d/554
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)

#normalizing the data
X = X / 255.

# (60K: Train) and (10K: Test)
X_train, X_test = X[:60000], X[60000:]
y_train, y_test = y[:60000], y[60000:]

In [3]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

for k in ['linear', 'poly', 'rbf', 'sigmoid']:
  for c in [1, 6, 16, 32]:
    model = SVC(kernel=k, C=c)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    test_accuracy = len([y_test[i] for i in range(0, len(y_test)) if y_test[i] == y_pred[i]]) / len(y_test)
    print("Testing Accuracy for kernel =", k, "and C =", c,"is ....", test_accuracy)
    test_error = 1-test_accuracy
    print("Testing Accuracy for kernel =", k, "and C =", c,"is ....", test_error)
    print("Confusion Matrix\n", confusion_matrix(y_test, y_pred))
    print("Classification Report", classification_report(y_test, y_pred))

Testing Accuracy for kernel = linear and C = 1 is .... 0.9404
Testing Accuracy for kernel = linear and C = 1 is .... 0.059599999999999986
Confusion Matrix
 [[ 957    0    4    1    1    6    9    1    0    1]
 [   0 1122    3    2    0    1    2    1    4    0]
 [   8    6  967   11    3    3    7    8   17    2]
 [   4    3   16  947    1   16    0    9   12    2]
 [   1    1   10    1  942    2    4    2    3   16]
 [  10    4    3   36    6  803   13    1   14    2]
 [   9    2   13    1    5   16  910    1    1    0]
 [   1    8   21   10    8    1    0  957    3   19]
 [   8    4    6   25    7   26    6    7  877    8]
 [   7    7    2   11   33    4    0   18    5  922]]
Classification Report               precision    recall  f1-score   support

           0       0.95      0.98      0.96       980
           1       0.97      0.99      0.98      1135
           2       0.93      0.94      0.93      1032
           3       0.91      0.94      0.92      1010
           4       0